### ISSUE TITLE
rSPDE from r-universe is broken

### ISSUE THREAD

**Issue by barracuda156** [davidbolin/rSPDE#6]
While package declares no compilation and the only dependency on `numDeriv`, and CRAN v. 2.3.1 installs just fine and as expected, r-universe v. 2.3.1.9000 breaks down spectacularly, trying to compile C++ code with undeclared deps and arbitrary flags leading to nowhere:

```
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-rSPDE/R-rSPDE/work/rSPDE" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-rSPDE/R-rSPDE/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library 
* installing *source* package ‘rSPDE’ ...
** using staged installation
** libs
g++ -O2 -Wall -Wextra -fpic  -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-rSPDE/R-rSPDE/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/INLA/include/ -I/usr/local/include/eigen3/ -I/usr/include/eigen3/ -c cgeneric_mvnormdens.cpp -o cgeneric_mvnormdens.o
cgeneric_mvnormdens.cpp:2:23: error: Eigen/Dense: No such file or directory
cgeneric_mvnormdens.cpp:3:28: error: Eigen/SparseCore: No such file or directory
cgeneric_mvnormdens.cpp: In function ‘double logmultnormvdens(int, double*, double*, double*)’:
cgeneric_mvnormdens.cpp:15: error: ‘Eigen’ has not been declared
cgeneric_mvnormdens.cpp:15: error: expected `;' before ‘prec_matrix’
cgeneric_mvnormdens.cpp:19: error: ‘prec_matrix’ was not declared in this scope
cgeneric_mvnormdens.cpp:23: error: ‘Eigen’ has not been declared
cgeneric_mvnormdens.cpp:23: error: expected `;' before ‘mean_vec’
cgeneric_mvnormdens.cpp:25: error: ‘mean_vec’ was not declared in this scope
cgeneric_mvnormdens.cpp:28: error: ‘Eigen’ has not been declared
cgeneric_mvnormdens.cpp:28: error: expected `;' before ‘val_vec’
cgeneric_mvnormdens.cpp:30: error: ‘val_vec’ was not declared in this scope
cgeneric_mvnormdens.cpp:33: error: ‘Eigen’ has not been declared
cgeneric_mvnormdens.cpp:33: error: ‘Eigen’ has not been declared
cgeneric_mvnormdens.cpp:33: error: ‘prec_matrix’ was not declared in this scope
cgeneric_mvnormdens.cpp:33: error: ‘chol’ was not declared in this scope
cgeneric_mvnormdens.cpp:37: error: ‘Eigen’ has not been declared
cgeneric_mvnormdens.cpp:37: error: expected `;' before ‘centered_vec’
cgeneric_mvnormdens.cpp:39: error: ‘centered_vec’ was not declared in this scope
cgeneric_mvnormdens.cpp:39: error: ‘val_vec’ was not declared in this scope
cgeneric_mvnormdens.cpp:39: error: ‘mean_vec’ was not declared in this scope
cgeneric_mvnormdens.cpp:43: error: ‘M_PI’ was not declared in this scope
cgeneric_mvnormdens.cpp:43: error: ‘log’ was not declared in this scope
make: *** [cgeneric_mvnormdens.o] Error 1
ERROR: compilation failed for package ‘rSPDE
```
It also randomly picks a wrong compiler, ignoring `R` settings.

**Comment by AlexandreBSimas** [comment]
Hello,

These source codes are not related to CRAN. They are to compile cgeneric interfaces for INLA. To maximize the compatibility with inla we request the gcc and g++ compilers (if you want to even increase the compatibility, you should use gcc-12 and g++-12). Unfortunately, it is difficult to make it automatic while maintaining compatibility with INLA.

We have a vignette about building from source:
https://davidbolin.github.io/rSPDE/articles/build_source.html
Please, take a look at it.

In your case It did not find eigen3 in the standard directories. If you installed/install eigen3 using brew, you should easily solve it by linking it to a standard folder:
sudo ln -s $(brew --prefix eigen)/include/eigen3 /usr/local/include/eigen3

You have a good point that we should make it explicit that the devel branch requires compilation. We will set the NeedsCompilation flag in DESCRIPTION on the devel and stable branches.

However, in the “cran” branch, you can find a version that does not require compilation.
It is the same version you obtain from the install.packages(“rSPDE”). In this case, the shared object you be used from your INLA installation.

So, if you want to avoid the trouble of compiling it, you can simply install the CRAN version and install INLA.
Otherwise, it is possible that you might need to clone and make some adjustments on the Makefile to be able to compile it.

Thanks for your message.
Best,
Alexandre

**Comment by barracuda156** [comment]
@vpnsctl Thank you for a detailed explanation.

Since we do not have INLA in Macports yet, there is no point to build an interface for it, so I will keep the package at CRAN version for the time-being, adding a note to portfile so that no one tries to update it to a newer R-universe version.

> You have a good point that we should make it explicit that the devel branch requires compilation. We will set the NeedsCompilation flag in DESCRIPTION on the devel and stable branches.

I think it should also set the said deps as required and not suggested.

> To maximize the compatibility with inla we request the gcc and g++ compilers (if you want to even increase the compatibility, you should use gcc-12 and g++-12).

I actually have `gcc-12` set as the compiler in `R`, but the code ignores that and picks a random `g++`, which gonna differ on various OS. IMHO this is a very fragile choice. `R` settings have a specific compiler for a reason.
Having said that, we can have this fixed locally in Macports, once INLA is brought in.

**Comment by AlexandreBSimas** [comment]
Hello,

Thank you for your comments. We also agree that this is the best option. We will restructure the branches a bit, and soon enough, the devel and stable branches will not require compilation (just like CRAN). However, the devel and stable branches will require INLA to be able to build all vignettes.

However, we would not like to add a dependency on INLA (instead of suggest), since most of the features of the package do not require INLA, and since INLA is not on CRAN, it would create a restriction on the package that is not really needed.

We will also consider you remaining points. I will then close the issue now.

Thanks.
Best,
Alexandre
